drop table if exists MENU_FOOD;
drop table if exists MENU;
drop table if exists FOOD;
drop table if exists RESTAURANT;
drop table if exists ADDRESS;





CREATE TABLE ADDRESS (
   ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   CITY varchar(255),
   COUNTRY varchar(255),
   STREET varchar(255),
   ZIPCODE varchar(255)
);


CREATE TABLE RESTAURANT (
   ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   NAME varchar(255) UNIQUE,
   ADDRESS_ID int
);
ALTER TABLE RESTAURANT ADD CONSTRAINT FK_RESTAURANT_ADDRESS_ID FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID);


CREATE TABLE MENU (
   ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   RESTAURANT_ID int NOT NULL,
   FROMDATE date,
   TODATE date
);
ALTER TABLE MENU ADD CONSTRAINT FK_MENU_Restaurant_ID FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(ID);


CREATE TABLE FOOD (
   ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
   CALORIES int,
   ISVEGAN bit DEFAULT 0 NOT NULL,
   NAME varchar(255) UNIQUE,
   PRICE int
);


CREATE TABLE MENU_FOOD (
   MENU_ID int NOT NULL,
   FOOD_ID int NOT NULL,
   PRIMARY KEY (MENU_ID, FOOD_ID)
);
ALTER TABLE MENU_FOOD ADD CONSTRAINT FK_MENU_FOOD_food_ID FOREIGN KEY (FOOD_ID) REFERENCES FOOD(ID);
ALTER TABLE MENU_FOOD ADD CONSTRAINT FK_MENU_FOOD_Menu_ID FOREIGN KEY (MENU_ID) REFERENCES MENU(ID);
