INSERT INTO TOPICS (ID, NAME, CREATION_TIMESTAMP)
VALUES (1, 'Kings', CURRENT_TIMESTAMP());

INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (10, 1, 'Choose all correct answers', 'Who is the king?', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (100, 10, 'Lenin', 0, CURRENT_TIMESTAMP()),
    (101, 10, 'Lenon', 0, CURRENT_TIMESTAMP()),
    (102, 10, 'Ganxta Zolee', 1, CURRENT_TIMESTAMP());





INSERT INTO TOPICS (ID, NAME, CREATION_TIMESTAMP)
VALUES (2, 'English', CURRENT_TIMESTAMP());

INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (20, 2, 'Choose one correct answer', '_____ they the first customers of the day?', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (200, 20, 'Who', 0, CURRENT_TIMESTAMP()),
    (201, 20, 'Was', 0, CURRENT_TIMESTAMP()),
    (202, 20, 'Were', 1, CURRENT_TIMESTAMP()),
    (203, 20, 'What', 0, CURRENT_TIMESTAMP());


INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (21, 2, 'Choose one correct answer', 'I can''t see anything in this ______.', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (210, 21, 'dark', 0, CURRENT_TIMESTAMP()),
    (211, 21, 'darkness', 1, CURRENT_TIMESTAMP()),
    (212, 21, 'darkening', 0, CURRENT_TIMESTAMP()),
    (213, 21, 'darker', 0, CURRENT_TIMESTAMP());





INSERT INTO TOPICS (ID, NAME, CREATION_TIMESTAMP)
VALUES (3, 'Japanese - Hiragana', CURRENT_TIMESTAMP());

INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (30, 3, 'Choose one correct answer', 'あ', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (300, 30, 'ka', 0, CURRENT_TIMESTAMP()),
    (301, 30, 'u', 0, CURRENT_TIMESTAMP()),
    (302, 30, 'a', 1, CURRENT_TIMESTAMP()),
    (303, 30, 'e', 0, CURRENT_TIMESTAMP());


INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (31, 3, 'Choose one correct answer', 'い', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (314, 31, 'ri', 0, CURRENT_TIMESTAMP()),
    (315, 31, 'i', 1, CURRENT_TIMESTAMP()),
    (316, 31, 'ha', 0, CURRENT_TIMESTAMP()),
    (317, 31, 'e', 0, CURRENT_TIMESTAMP());


INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (32, 3, 'Choose one correct answer', 'う', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (324, 32, 'no', 0, CURRENT_TIMESTAMP()),
    (325, 32, 'i', 0, CURRENT_TIMESTAMP()),
    (326, 32, 'o', 0, CURRENT_TIMESTAMP()),
    (327, 32, 'u', 1, CURRENT_TIMESTAMP());


INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (33, 3, 'Choose one correct answer', 'え', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (334, 33, 'o', 0, CURRENT_TIMESTAMP()),
    (335, 33, 'e', 1, CURRENT_TIMESTAMP()),
    (336, 33, 'mi', 0, CURRENT_TIMESTAMP()),
    (337, 33, 'wa', 0, CURRENT_TIMESTAMP());


INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (34, 3, 'Choose one correct answer', 'お', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (344, 34, 'o', 1, CURRENT_TIMESTAMP()),
    (345, 34, 'ki', 0, CURRENT_TIMESTAMP()),
    (346, 34, 'ho', 0, CURRENT_TIMESTAMP()),
    (347, 34, 'e', 0, CURRENT_TIMESTAMP());





INSERT INTO TOPICS (ID, NAME, CREATION_TIMESTAMP)
VALUES (4, 'Vegyes', CURRENT_TIMESTAMP());

INSERT INTO QUIZZES (ID, TOPIC_ID, DESCRIPTION, QUESTION, CREATION_TIMESTAMP)
VALUES (40, 4, 'Jelöld meg az összes helyes választ!', 'Mit csinál a kiskacsa?', CURRENT_TIMESTAMP());

INSERT INTO CHOICES (ID, QUIZ_ID, ANSWER, CORRECT, CREATION_TIMESTAMP)
VALUES
    (400, 40, 'tusol', 0, CURRENT_TIMESTAMP()),
    (401, 40, 'fürdik', 1, CURRENT_TIMESTAMP()),
    (402, 40, 'disznót vág', 0, CURRENT_TIMESTAMP());
